### ISSUE TITLE
UBLExtension in InvoiceType with incorrect namespace prefix

### ISSUE THREAD

**Issue by qgnox** [phax/ph-ubl#1]
Hi, first of all thanks for this API.

My issue is that when I create an InvoiceType document and added a UBLExtensions when is marshalled to DOM the namespace prefix appears as cec: 

```html
<cec:UBLExtensions xmlns:cec="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2">
<cec:UBLExtension>
<cec:ExtensionContent/>
</cec:UBLExtension>
</cec:UBLExtensions>
```

instead of the one used in the xsd for UBL-Invoice-2.0.xsd ext:

```html
xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
```
Any ideas ?

**Comment by ssdf34** [comment]
Hi Mr. Philip

How I  can replace "cec" with "ext"?
