### ISSUE TITLE
XmlAdapter

### ISSUE THREAD

**Issue by umitcel** [phax/ph-ubl#13]
Hello, great work,

I wonder if we can define custom XmlAdapter annotations for types.
Thank you.

**Comment by phax** [comment]
Hi. Please elaborate a bit on what you need. It may be done by extended the ubl-jaxb-plugin???

**Comment by umitcel** [comment]
Hi Philip,
For example I want amountType render as 2 decimal places. By the way I handled it wit scale property of BigDecimal.

**Comment by phax** [comment]
Ah okay. Yes, these kind of requirements are better handled on the Java level :)
