### ISSUE TITLE
ESuccess errors when debugging

### ISSUE THREAD

**Issue by osvalr** [phax/ph-ubl#14]
I begin to test this library, and I noticed that `UBL20Writer` returns "FAILURE" but as far as I can see there is no hint what is maybe wrong with the invoice created.

How can I get some more verbose error output when it fails?

**Comment by phax** [comment]
You need to set an event handler as in `writer.setValidationEventHandler (new LoggingValidationEventHandler ())`.
There are different kind of validation handlers. See package `com.helger.jaxb.validation` in project `ph-jaxb` (transitively included).
hth

**Comment by osvalr** [comment]
Thanks @phax, closing this

**Comment by phax** [comment]
@osvalr thanks for following up. If you have further questions, just create a new issue :)
