### ISSUE TITLE
How should create an Extension on Java Code

### ISSUE THREAD

**Issue by richardhell** [phax/ph-ubl#2]
Hey there 

Dude that's amazing API, please help me with guidelines to create an extension to add on a ExtensionContent object.

Thanks a lot.

**Comment by phax** [comment]
Hey!
I assume you mean the UBL 2.0 ExtensionContent field - right?
This type allows ONLY for XML content.
If so, you must build an org.w3c.dom.Element (e.g. by parsing an existing XML or by creating a new Document from scratch) and feed it into an instance of `ExtensionContentType`.
hth

**Comment by richardhell** [comment]
Yeah, I'm using UBL 2.0. In my case the extension is so simply:

```
<sac:AdditionalInformation>
	<sac:AdditionalMonetaryTotal>
		<cbc:ID>1001</cbc:ID> 
		<cbc:PayableAmount/@currencyID="PEN">22.50</cbc:PayableAmount>
	</sac:AdditionalMonetaryTotal>

	<sac:AdditionalMonetaryTotal>
		<cbc:ID>1002</cbc:ID>
		<cbc:PayableAmount/@currencyID="PEN">456.78</cbc:PayableAmount> 
	</sac:AdditionalMonetaryTotal>
</sac:AdditionalInformation>
```

There is necesary to create an Document or can create a Class and Map with XML?

Thanks

**Comment by phax** [comment]
You need to parse the XML with an XML Parser and put the "documentElement" from the resulting parsing into the Extension element.
Maybe you can map it somehow, but there is no predefined support for this!

**Comment by richardhell** [comment]
thanks dude.
