### ISSUE TITLE
Open PEPPOL support

### ISSUE THREAD

**Issue by horiaradu** [phax/ph-ubl#21]
Is there any support for generating / reading Open PEPPOL formats of documents?

**Comment by phax** [comment]
Yes, PEPPOL UBL is a "profile" or "subset" of UBL 2.1 so easily usable.
So all PEPPOL documents adhere to the UBL 2.1 XSDs and adds additional Schematron rules on top of it.
Does that answer your question?

**Comment by horiaradu** [comment]
Thanks a lot for the reply, maybe you can share a snippet / example showing how I can use a `UBL21Writer` to produce a PEPPOL UBL?

**Comment by phax** [comment]
I don't have code to create a valid PEPPOL invoice from scratch, but I have code to create an "arbitrary" invoice at https://github.com/phax/ph-ubl/blob/master/ph-ubl21/src/test/java/com/helger/ubl21/CreateInvoiceFromScratchFuncTest.java
and example PEPPOL files reside at https://github.com/OpenPEPPOL/peppol-bis-invoice-3/tree/master/rules/examples
You can than test your UBL Instances online at https://peppol.helger.com/public/locale-en_US/menuitem-validation-bis2

**Comment by phax** [comment]
Do you need more input, or can this issue be closed?

**Comment by horiaradu** [comment]
Thanks a lot for the quick reply. I've looked over the PEPPOL standard and used the `InvoiceType` to construct a compliant document.

I believe this can be closed. If I run into any issues, I will write :)

**Comment by phax** [comment]
Thanks for the feedback and good luck.
You might consider giving https://github.com/phax/ph-bdve a look, to validate your instances before sending them out.
