### ISSUE TITLE
Support for CIUS-ES-FACE

### ISSUE THREAD

**Issue by dgrmunch** [phax/ph-ubl#23]
Hi!

Please, can you let me know if the ph-ubl library includes support for CIUS-ES-FACE?

https://administracionelectronica.gob.es/ctt/resources/Soluciones/334/Descargas/CIUS-ES-FACE-1-0-0.pdf?idIniciativa=334&idElemento=15972

In case the answer is negative, how could it be included in the UBL 2.1 lib?

Thanks!

**Comment by phax** [comment]
A CIUS is defined to be a total subset of the EN, and as such, every CIUS must be readable with the generic superset parser.
Therefore, without testing it, I'm pretty sure, the CIUS can be read with the UBL 2.1 parser from this project. And btw. extending an XML Schema is totally out of scope for a CIUS, so this generic UBL 2.1 parser can even read Extensions :)

**Comment by phax** [comment]
I'm closing this one as well - same CIUS rules apply as for CII
