### ISSUE TITLE
Warning Message

### ISSUE THREAD

**Issue by alvarezpablo** [phax/ph-ubl#3]
Hello,

I'm starting to test your library and I got a warning message with the method readXMLDOM, the XML is loaded, but the message is:

WARN com.helger.commons.xml.sax.ReadableResourceSAXInputSource - Failed to open input stream for [cpPath=C:/temp/Invoice.xml; urlResolved=true; URL=null]

Maybe is not an important message, but I prefer ask you.

Best Regards,

Pablo Alvarez

The simple code is: 		

	    final Document xmlDoc = DOMReader.readXMLDOM (new ClassPathResource (strFilename),
	                                                  new DOMReaderSettings ().setSchema (EUBL20DocumentType.INVOICE.getSchema ()));
	      
	    final InvoiceType xmlUBLObject = UBL20Reader.readInvoice (xmlDoc);
	    
	    String s = xmlUBLObject.getAccountingSupplierParty().getCustomerAssignedAccountIDValue();

**Comment by phax** [comment]
Hi!
You are mixing classpath resources with file system resources.
If you have a filename, you should either use `UBL20Reader.readInvoice (new File (strFilename))` or alternatively use `FileSystemResource` instead of `ClassPathResource`.
And Btw. you don't need to pass in the schema manually. It is done automatically within `readInvoice` by the JAXB Unmarshaller.
hth

**Comment by alvarezpablo** [comment]
Hello Phlip,

I tried with UBL20Reader.readInvoice (new File (strFilename))  and it works.

And now just I need to capture schema errors, with the XML file has schema
errors I got a null object, How I can get this errors?

Best Regards,

Pablo Alvarez


2015-06-08 2:18 GMT-03:00 Philip Helger <notifications@github.com>:

**Comment by phax** [comment]
Hi Pablo!
The simplest thing to do, is to pass in an additional `ValidationEventHandler` that collects all errors. Use e.g. 
```java
CollectingValidationEventHandler aEventHandler = new CollectingValidationEventHandler ();
InvoiceType aInvoice = UBL20Reader.readInvoice (new File (strFilename), aEventHandler);
if (aInvoice == null)
{
  IResourceErrorGroup aErrors = aEventHandler.getResourceErrors ();
  // ... do something with the information ....
}
```

**Comment by alvarezpablo** [comment]
thank you!!!

2015-06-09 6:15 GMT-03:00 Philip Helger <notifications@github.com>:
