### ISSUE TITLE
question about extension content

### ISSUE THREAD

**Issue by jpaezlancheros** [phax/ph-ubl#30]
Hi Phillip

I have a question in ubl element ExtensionContent when I put in any (.setAny()) a custom  element (Colombia)  for instance "DianExtensionsType" the result xml is interrupted and not written . is there any consideration to have? 

if I create a Dom document and add the node with setAny() as is in scratch example, it works well, but in the case i use an  XmlType it doesn't.

**Comment by phax** [comment]
The simplest way is to create an `DianExtensionsType` instance and marshal it to a DOM `Element`. 
Than just pass the `Element` to `setAny`.

I am not sure if there is another way to do it - I use it in the same way.

**Comment by jpaezlancheros** [comment]
Thanks. I figure it out.
By the way  added these https://www.dian.gov.co/impuestos/factura-electronica/Documents/Caja-de-Herramientas-Nomina-Electronica-V1-0.zip documents to dianUBL (UBL for colombia)

**Comment by phax** [comment]
Okay great. As I don't speak Spanish, can you give a brief description what that excatly is? Thanks

**Comment by jpaezlancheros** [comment]
oh, they added two documents  to Dian Ubl  documents (custom document really) 
-nominaIndiviudual  (pay roll receipt)
-nominaIndividualDeAjuste (pay roll adjust)

they use some elements of ubl. but thats it. defined in XSL folder

**Comment by phax** [comment]
Ah cool. So you mean I could add them to the library:)

**Comment by phax** [comment]
This will be fixed in 6.6.1 - than the namespaces are forced to "sts" for the DianExtension
