### ISSUE TITLE
Wrong IssueDate format value

### ISSUE THREAD

**Issue by brunogptavares** [phax/ph-ubl#32]
Using version 6.50 of  ph-ubl21, when I write to string the UBL21Invoice the IssueDate field apears like this:
<cbc:IssueDate>2021-03-24Z</cbc:IssueDate>

If I use version 6.4.3 of ph-ubl21 it apears like this:
<cbc:IssueDate>2021-03-24</cbc:IssueDate>
witch is the correct format against the CIUS-PT validator.

**Comment by phax** [comment]
Version 6.6.0 fixes this, by using `XMLOffset(Date|Time|DateTime)`
