### ISSUE TITLE
Determine Type of document from XML String

### ISSUE THREAD

**Issue by kurbhatt** [phax/ph-ubl#37]
I am trying to parse XML string to UBL document/object.
Here's the code:
`InvoiceType ublInvoice = UBL21Reader.invoice().read(xmlString);`
This works when I know the type of document so I can easily read with UBL21Reader.
In case if I do not have the type then how can I parse XML string to UBL document object?
Is there any way of generic UBL document or any way to extract document/invoice type code from XML?
Is there any provider in UBL21Reader or other class through which I can determine the type of document from an XML string?
So based on that type I can read through UBL21Reader.

**Comment by phax** [comment]
Nope there is not, because if you don't know the document type, the Reader xannot apply the correct XSDs.
Please read as ordinary XML via a DOM based XML reader, and check the namespace URI kf the root element against the one from EUBL21DocumentType (or so - am afk)

**Comment by kurbhatt** [comment]
Hello @phax
Thanks for the details.
I have read normal XML through Document and have read root tag element (Invoice, CreditNote, DebitNote, ...), based on that I have prepared enum mapping for root node/tag name to UBL document type, and based on that I am reading UBL document. A namespace is also an option but after reading namespace also we'll get the root tag name(I think) so I have directly used the tag name.
Please correct me if I am wrong at any place.
If seems good you can close the issue.
