### ISSUE TITLE
How to add UBLDocumentSignatures in UBL Extension?

### ISSUE THREAD

**Issue by kurbhatt** [phax/ph-ubl#39]
I have created 1 UBL document InvoiceType. It has all the required details.
Now I want to add a Signature to the UBL document. The Extension will be used for this AFAIK.
I have tried to find out this but I am not able to find the solution.

I tried with xades4j but there's 1 issue, it creates a Signature directly in Document(using **ds:Signature**), not in the Extension. I passed the UBL XML string to xades4j.
I want it to be in structure:

`<ext:UBLExtensions>
    <ext:UBLExtension>
        <ext:ExtensionURI>urn:oasis:names:specification:ubl:dsig:enveloped:xades</ext:ExtensionURI>
        <ext:ExtensionContent>
            <sig:UBLDocumentSignatures xmlns:sac="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2" xmlns:sbc="urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2" xmlns:sig="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2">
                <sac:SignatureInformation>
                    <cbc:ID>urn:oasis:names:specification:ubl:signature:1</cbc:ID>
                    <sbc:ReferencedSignatureID>urn:oasis:names:specification:ubl:signature:Invoice</sbc:ReferencedSignatureID>
                    <ds:Signature Id="signature" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                        <ds:SignedInfo>
`

Please suggest me way to add a signature in the UBL extension.

**Comment by phax** [comment]
I recommend to use the DSS library to add electronic signatures.
See https://github.com/esig/dss/ for details.
