### ISSUE TITLE
how to change cbc:IssueTime formats

### ISSUE THREAD

**Issue by ssdf34** [phax/ph-ubl#40]
Hi,
 How I can change cbc:IssueTime formats from <cbc:IssueTime>**17:18:50.0**</cbc:IssueTime>
to <cbc:IssueTime>**17:18:50**</cbc:IssueTime> whiteout nanosecond?

**Comment by phax** [comment]
This is an issue that occurs from Java 9 on, if I remember correctly.
The key point here is to limit the precision on any time and dateTime object to milliseconds. I am e.g. using `truncatedTo (ChronoUnit.MILLIS)` internally.

**Comment by ssdf34** [comment]
Thank you for your fast replay but when I use  LocalTime  InviceIssiuTime_S = LocalTime.now();    
   aInvoice.setIssueTime(InviceIssiuTime_S.truncatedTo(ChronoUnit.MILLIS));
I got <cbc:IssueTime>17:43:08.498</cbc:IssueTime>
when I use  LocalTime  InviceIssiuTime_S = LocalTime.now();
   aInvoice.setIssueTime(InviceIssiuTime_S.truncatedTo(ChronoUnit.SECONDS));
I got <cbc:IssueTime>17:51:34.0</cbc:IssueTime>
and I remove ".0" from IssueTime

**Comment by ssdf34** [comment]
How I can remove ".0" from  the last

**Comment by phax** [comment]
Ah you mean, you want to totally remove the fraction seconds part....
May I ask why? Syntactically that is totally fine and it makes semantically no difference.....
(I can't think of any quick fix for this)

**Comment by ssdf34** [comment]
because it is requirement in our country in UBL evince

**Comment by phax** [comment]
Technically stupid requirement but okay.
Can you try
```xml
aInvoice.setIssueTime(InviceIssiuTime_S.truncatedTo(ChronoUnit.MINUTES));
```

**Comment by phax** [comment]
doesn't work

**Comment by phax** [comment]
Bug on my side.... :(

**Comment by ssdf34** [comment]
When I try aInvoice.setIssueTime(InviceIssiuTime_S.truncatedTo(ChronoUnit.MINUTES));
I have got

<cbc:IssueTime>19:05**:00.0**</cbc:IssueTime>

**Comment by phax** [comment]
Yes yes - as I mentioned previously it's a bug on my side. Working on it

**Comment by phax** [comment]
Please update your "ph-commons" dependency to `10.1.3` (assuming you use the latest ph-ubl version) to resolve the issue

**Comment by ssdf34** [comment]
Thank you It is working fine now and I appreciate your kind cooperation and quick response

**Comment by phax** [comment]
Great - thanks for testing. I will create an updated 6.6.3 release to avoid that manual cause!
