### ISSUE TITLE
UBLExtensions

### ISSUE THREAD

**Issue by ssdf34** [phax/ph-ubl#46]
when I generate the xml file UBLExtensions shown like that  <cec:UBLExtensions> but it supposed to be like that <ext:UBLExtensions> as in http://www.datypic.com/sc/ubl21/e-ext_UBLExtensions.html

**Comment by phax** [comment]
Maybe this example code shows you, how to handle UBL extensions: https://github.com/phax/ph-ubl/blob/master/ph-ubl-dian/src/test/java/com/helger/dianubl/DianUBLFuncTest.java

**Comment by phax** [comment]
Did that help you, or do you have any more specific question @ssdf34  ?
