### ISSUE TITLE
 In UBLExtension How I can replace prefix "cec" with "ext"?

### ISSUE THREAD

**Issue by ssdf34** [phax/ph-ubl#49]
Hi Mr. Philip

 In UBLExtension How I can replace prefix "cec" with "ext"?

**Comment by phax** [comment]
Hi  @ssdf34 Please see this code snippet on how to do it:
https://github.com/phax/ph-ubl/issues/34#issuecomment-840249899

hth

**Comment by ssdf34** [comment]
Dear  Mr. Philip
I appreciate your speedy help. Thank you very much for your help. The problem has been resolved.
