### ISSUE TITLE
UBL invoice namespacing

### ISSUE THREAD

**Issue by ri4a** [phax/ph-ubl#5]
Hi Philip,

First of all, thanks for your great library.

I want to use it to create an invoice and then marshal it to XML with `UBL21Writer.writeInvoice`. That works, but I have a problem with the namespacing in the resulting XML. It looks something like

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ns4:Invoice
    xmlns="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
    xmlns:ns2="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
    xmlns:ns3="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
    xmlns:ns4="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2">
    <UBLVersionID>2.1</UBLVersionID>
    <CustomizationID>urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol4a:ver2.0:extended:urn:www.simplerinvoicing.org:si:si-ubl:ver1.1.x</CustomizationID>
...
</ns4:Invoice>
```

The following reproduces this (without creating a full valid invoice, but it illustrates the problem in less lines):

```java
InvoiceType testInvoice = new InvoiceType();
IResourceErrorGroup aErrors = UBL21Validator.validateInvoice(testInvoice);
if (aErrors != null) {
    System.out.println("Errors: " + aErrors.toString());
    System.exit(1);
} else {
    System.out.println("No errors");
}
```

Obviously, there are errors and I get

> *The content of element '__ns4:Invoice__' is not complete*.

How do I get the correct namespaces, what am I doing wrong?

Thanks!

**Comment by phax** [comment]
Hi!
In case you mean ns1, ns2 etc. are wrong: there is a known error with the ph-commons version used by ph-ubl 4.0.0. If you switch to ph-commons 6.2.1 and ph-jaxb 6.2.1 (simply include it in the project where you include ph-ubl), you should get cac, cbc etc. namespace prefixs.

In case you think that something else is wrong, please clarify in more detail what's bugging you :)

// Philip

**Comment by ri4a** [comment]
Thanks for the fast response - that works like a charm (and yes, I meant the ns# namespaces :smile:)

Except for the root namespace, which is still ns4:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ns4:Invoice xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
xmlns:cec="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
xmlns:ns4="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2">
<cbc:UBLVersionID>2.1</cbc:UBLVersionID>
...
</Invoice>
```

I tried adding a package-info.java with an @javax.xml.bind.annotation (https://docs.oracle.com/javase/7/docs/api/javax/xml/bind/annotation/XmlSchema.html):

```java
@javax.xml.bind.annotation.XmlSchema(
        namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @javax.xml.bind.annotation.XmlNs(
                        namespaceURI = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2",
                        prefix = ""
                )
        }
)
package com.storecove.app.java;
```

but I didn't get that to work yet. Is there another solution?

Thanks,

Michael

**Comment by phax** [comment]
Glad the basic things worked.
Modifying the root namespace prefix is currently not supported. There is a class `UBL21NamespaceContext` that does the trick, but it cannot be customized. I will add this for the next release and keep you posted.

**Comment by ri4a** [comment]
Perfect, thanks! Closing.

**Comment by phax** [comment]
New version 4.5.0 provides you the ability. Because of a changed (and simplified) API you may want to look at the examples.

**Comment by ri4a** [comment]
Is in our production environment - many thanks Philip.

**Comment by phax** [comment]
Your welcome. The new default namespace mapping should already to the trick for you :)
