### ISSUE TITLE
Invoice xmlns prefix 

### ISSUE THREAD

**Issue by alkahtani** [phax/ph-ubl#50]
I have followed the CreateInvoiceFromScratch and the invoice successfully created in the Target folder but i have an issue with  the prefix of  CommonExtensionComponents namespace  `xmlns:cec="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2`  , is it possible to have it  "ext" like `xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2` as it is important for me to do validation and integration with existing systems

Please help.

Thank you

**Comment by phax** [comment]
Please see old issues like #49  which eg. points to #34 
Enjoy :)

**Comment by alkahtani** [comment]
Dear @phax very much appreciated your help  , Thank you .
