### ISSUE TITLE
Failed to add multiple scheme ID with value in PartyIdentificationType for UBL 2.1 version 9.0.0

### ISSUE THREAD

**Issue by soowc** [phax/ph-ubl#62]
Hi,

Sorry for disturb. Encountered issue when wanted to add multiple ID in PartyIdentificationType.
Checked and there is no addID in PartyIdentificationType library. Am I doing correctly on this?

    final PartyIdentificationType aIdentification = new PartyIdentificationType();
    IDType aID = new IDType();
    aID.setSchemeID("TIN");
    aID.setValue("TINNo1");

    IDType bID = new IDType();
    bID.setSchemeID("NRIC");
    bID.setValue("NRICNo1");
    
    aIdentification.setID(aID);
    aIdentification.setID(bID);

 System.out.println("aIdentification ::: "+aIdentification.toString());

Output:
id=[IDType@0x1ed4004b: schemeAgencyID=null; schemeAgencyName=null; schemeDataURI=null; schemeID=NRIC; schemeName=null; schemeURI=null; schemeVersionID=null; value=NRICNo1]]

**Comment by phax** [comment]
Hi. Don't call `setID` but `addID`.
hth

**Comment by soowc** [comment]
Hi,

Thank you for clarifying. 
The sample output I received, which included multiple rows of ID in Party Identification, prompted the question. 

This clarification has been immensely helpful, and I'm delighted to hear that the library is working smoothly for you. Thank you!
