### ISSUE TITLE
sts namespace in Invoice documents

### ISSUE THREAD

**Issue by hlbarragan** [phax/ph-ubl#64]
Hi, I'm using ph-ubl-dian library for creating and managing XML documents through an oasis.names.specification.ubl.schema.xsd.invoice_21.InvoiceType instance.

For the creation of the InvoiceType Instance, I'm using the next piece of code where PLANTILLA_FACTURA_XML is the route of a XML template:

`final InvoiceType invoice = DianUBLMarshaller.invoice().read(ContenidoFacturaHelper.class.getClassLoader().getResourceAsStream(PLANTILLA_FACTURA_XML));`

The definition of root and DianExtensions nodes is as follows:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Invoice
	xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
	xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
	xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
	xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
	xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
	xmlns:sts="dian:gov:co:facturaelectronica:Structures-2-1"
	xmlns:xades="http://uri.etsi.org/01903/v1.3.2#"
	xmlns:xades141="http://uri.etsi.org/01903/v1.4.1#"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2     http://docs.oasis-open.org/ubl/os-UBL-2.1/xsd/maindoc/UBL-Invoice-2.1.xsd">
	<ext:UBLExtensions>
		<ext:UBLExtension>
			<ext:ExtensionContent>
				<sts:DianExtensions>`

When the instance is filled with data and then  transformed into an OutputStream for file creation, or just a String variable for logging, the resulting XML has the next content in the root and DianExtensions nodes:

`<?xml version="1.0" encoding="UTF-8"?>
<Invoice
	xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
	xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
	xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"
	xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">
	<ext:UBLExtensions>
		<ext:UBLExtension>
			<ext:ExtensionContent>
				<sts:DianExtensions
					xmlns:sts="dian:gov:co:facturaelectronica:Structures-2-1">`

As can be seen there are some namespaces originally defined in the root node of the XML template like xmlns:sts="dian:gov:co:facturaelectronica:Structures-2-1" that are now defined in the DianExtensions node of the created XML file, but the system of tax and customs agency in Colombia specifically requires that sts namescpace to be defined in the root node.

This is the way I'm creating the XML file or the string for logging based on the InvoiceType instance invoice

`// os is an OutputStream instance
DianUBLMarshaller.invoice().write(invoice, os);`

`String xmlStructure = DianUBLMarshaller.invoice().setFormattedOutput(true).getAsString(invoice)`

So the purpose of this post is to know if this is possible, and how it could be done.

I've tried some options suggested in other threads like [this](https://github.com/phax/ph-ubl/issues/20#issuecomment-581974191) with the same results.

**Comment by phax** [comment]
Well, the problem seems to be, that the customs agency of Colombia is interpreting the XML standard in a very interesting way. Please see https://www.w3.org/TR/REC-xml-names/ on how XML Namespaces are supposed to be used.

This library uses JAXB as the underlying marshaller and to the best of my knowledge it doesn't offer control of "where" to place namespace prefixes inside a file.

So I am afraid there is no "default way" to solve your problem, except for later manipulation of the result as a "text string" which is totally against how XML is intended to be used.

hth

**Comment by hlbarragan** [comment]
That's just wath I did to solve that problem, It was necesary to edit the file to move that NS definition when is ful with the business data.

Thanks for your quick answer.

**Comment by phax** [comment]
Maybe you can reach out to the Colombina customs support and let them know, that there is room for improvement in their solution ;-)
