### ISSUE TITLE
Add xPath to TransformType

### ISSUE THREAD

**Issue by kahken888** [phax/ph-ubl#66]
Hi Phax, i would like to know how to add xPath to TransformType like the example below. I tried many method but unable to add like the example
Can you help to explain more about the xPath or provide example code how to add?

Example:
```
<ds:SignedInfo>

<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
<ds:Reference Id="id-doc-signed-data" URI="">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
<ds:XPath>not(//ancestor-or-self::ext:UBLExtensions)</ds:XPath>
</ds:Transform>
<ds:Transform Algorithm="http://www.w3.org/TR/1999/REC-xpath-19991116">
<ds:XPath>not(//ancestor-or-self::cac:Signature)</ds:XPath>
</ds:Transform>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>9Ajw/lNpwRWfqdrLeKFePPZJnBXoT9eKzThl1NRflzY=</ds:DigestValue>
</ds:Reference>
<ds:Reference Type="http://www.w3.org/2000/09/xmldsig#SignatureProperties" URI="#id-xades-signed-props">
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>dgpDYlwgaRF542ogPTVcdHAQ1q47QgDfd6m+GeCgwfE=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>OzgXCgMuioS9zGu/X0hywz+s3vkZVwkuNlefT8Ni1LjOEJqbUw2YFy9IzqxWrnpi6k4JzeHE40cHPFuXwDFkEi4/1MPCbyOPi/EWvc1rp/8sQoaMWG5e4965xKQH7lfX+WYpqhIWRyEEb4X5teVn/jI7u2AuwWlQSuQRHismaF2YJqtwey1VyxJE805wuWWB/3itlzlMSVbO7B9tLpPIL0f6WqENXFEa8yD4kisY9qb6wehIK9fDg3pfaY4g4xzF/ba8H+6h22QNNok3RfXyuWvna8XuhrGR6gOh/5s6FdPxcb1A9aAaB3OUuk+chNxdptdLyC9EZ6AnoJE8jy5ruA==</ds:SignatureValue>
</ds:SignedInfo
```

**Comment by kahken888** [comment]
im using javax.xml.xpath.xPath and java default. Can teach me how to add xPath follow the value of example first？

**Comment by phax** [comment]
@kahken888 see the above commit for an example how to use namespaces in XPath

**Comment by kahken888** [comment]
Sry phax, I think my question was no clear for you. Let me explain again. I would like to add the xPath with value "not(//ancestor-or-self::ext:UBLExtensions)" to TransformType.addContent() but i keep hit error for this. Can you kindly advice me?

Example:
`XPathFactory xPathFactory = XPathFactory.newInstance();
            XPath xPath = xPathFactory.newXPath();
            MapBasedNamespaceContext nsContext = new MapBasedNamespaceContext();
            nsContext.addMapping("ds", "http://www.w3.org/2000/09/xmldsig#");
            xPath.setNamespaceContext(nsContext);
            xPath.compile("not(//ancestor-or-self::ext:UBLExtensions)");
            TransformType transformType =new TransformType();
            transformType.addContent(xPath);
            transformType.setAlgorithm(transformsString);`

**Comment by phax** [comment]
The "ext" namespace mapping is missing in the namespace context map.
And you need to "evaluate" the XPath expression and not just "compile" it. On evaluation you provide the context node, which in your case is the whole document I guess

**Comment by kahken888** [comment]
Thank you very much, the problem have fixed
