### ISSUE TITLE
Add xPath to TransformType

### ISSUE THREAD

**Issue by hyououou** [phax/ph-ubl#67]
hi:

TransformType transformType1 = new TransformType();
transformType1.setAlgorithm("http://www.w3.org/TR/1999/REC-xpath-19991116");

XPathFactory xPathFactory = XPathFactory.newInstance();
XPath xPath = xPathFactory.newXPath();
MapBasedNamespaceContext nsContext = new MapBasedNamespaceContext();
nsContext.addMapping("ext", "http://www.w3.org/2000/09/xmldsig#");
nsContext.addMapping("ds", "http://www.w3.org/2000/09/xmldsig#");
xPath.setNamespaceContext(nsContext);
xPath.compile("not(//ancestor-or-self::ext:UBLExtensions)");

transformType1.addContent(xPath);

Element aSignaturesElement = new UBL21Marshaller.UBL21JAXBMarshaller<>(UBLDocumentSignaturesType.class,
                                UBL21Marshaller.getAllBaseXSDs(),
                                ObjectFactory._UBLDocumentSignatures_QNAME).getAsElement(ublDocumentSignaturesType);

jakarta.xml.bind.JAXBException: class com.sun.org.apache.xpath.internal.jaxp.XPathImpl以及其任何超类对此上下文都是未知的。

![微信截图_20241217124010](https://github.com/user-attachments/assets/1c955704-b77c-4762-afba-75b73a34215a)

**Comment by phax** [comment]
You cannot mix JAXB components (class `TransformType`) and programmatic components (`XPath´).
You need to add a `JAXBElement<String>` to the `TransformType`.

Here's some untested example code:
```xml
var of = new com.helger.xsds.xmldsig.ObjectFactory ();
TransformType transformType1 = new TransformType();
transformType1.setAlgorithm("http://www.w3.org/TR/1999/REC-xpath-19991116");
transformType1.addContent ().add (of.createTransformTypeXPath ("not(//ancestor-or-self::ext:UBLExtensions)"));

Element aSignaturesElement = new UBL21Marshaller.UBL21JAXBMarshaller<>(UBLDocumentSignaturesType.class,
UBL21Marshaller.getAllBaseXSDs(),
ObjectFactory._UBLDocumentSignatures_QNAME).getAsElement(ublDocumentSignaturesType);
```

The namespace mapping needs to be available to the processor, that actually performs the transformation, so I **think** that adding `ext` as a namespace into the XML instance (`xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"`)

**Comment by hyououou** [comment]
hi:

Sorry for disturbing you again

                        // Object
                        com.helger.xsds.xmldsig.ObjectType objectType = new ObjectType();
                        QualifyingPropertiesType qualifyingPropertiesType = new QualifyingPropertiesType();
                        qualifyingPropertiesType.setTarget("signature");
                        SignedPropertiesType signedPropertiesType = new SignedPropertiesType();
                        signedPropertiesType.setId("id-xades-signed-props");
                        qualifyingPropertiesType.setSignedProperties(signedPropertiesType);
                        SignedSignaturePropertiesType signedSignaturePropertiesType = new SignedSignaturePropertiesType();
                        signedSignaturePropertiesType.setSigningTime(LocalDateTime.now());
                        com.helger.xsds.xades132.CertIDListType certIDListType = new CertIDListType();
                        com.helger.xsds.xades132.CertIDType certIDType = new CertIDType();
                        com.helger.xsds.xades132.DigestAlgAndValueType digestAlgAndValueType = new DigestAlgAndValueType();
                        com.helger.xsds.xmldsig.DigestMethodType digestMethodType = new DigestMethodType();
                        digestMethodType.setAlgorithm("http://www.w3.org/2001/04/xmlenc#sha256");
                        digestAlgAndValueType.setDigestMethod(digestMethodType);
                        digestAlgAndValueType.setDigestValue("YTJkM2JhYTcwZTBhZTAxOGYwODMyNzY3NTdkZDM3YzhjY2IxOTIyZDZhM2RlZGJiMGY0NDUzZWJhYWI4MDhmYg==".getBytes());
                        certIDType.setCertDigest(digestAlgAndValueType);
                        com.helger.xsds.xmldsig.X509IssuerSerialType x509IssuerSerialType = new X509IssuerSerialType();
                        x509IssuerSerialType.setX509IssuerName("CN = Contoso Malaysia Sdn Bhd, E = noemail@contoso.com, OU = Contoso Malaysia Sdn Bhd, O = Contoso Malaysia Sdn Bhd, C = MY");
                        x509IssuerSerialType.setX509SerialNumber(new BigInteger("2475382886904809774818644480820936050208702411"));
                        certIDType.setIssuerSerial(x509IssuerSerialType);
                        certIDListType.addCert(certIDType);
                        signedSignaturePropertiesType.setSigningCertificate(certIDListType);
                        signedPropertiesType.setSignedSignatureProperties(signedSignaturePropertiesType);
                        qualifyingPropertiesType.setSignedProperties(signedPropertiesType);
                        objectType.addContent(qualifyingPropertiesType);
                        signatureType.addObject(objectType);

Element aSignaturesElement = new UBL21Marshaller.UBL21JAXBMarshaller<>(UBLDocumentSignaturesType.class,
UBL21Marshaller.getAllBaseXSDs(),
ObjectFactory._UBLDocumentSignatures_QNAME).getAsElement(ublDocumentSignaturesType);

jakarta.xml.bind.JAXBException: class com.helger.xsds.xades132.QualifyingPropertiesType以及其任何超类对此上下文都是未知的。

![22222](https://github.com/user-attachments/assets/a42537b2-c6ef-449c-bbe8-c49a8ce2cbbf)

**Comment by phax** [comment]
You may want to look for the example code created for #63

**Comment by hyououou** [comment]
I didn't get it.
Do you have sample code?

**Comment by phax** [comment]
See the above linked example file.
The problem is, that your element is not meant to be rendered alone - it will work when serialized in the context of an Invoice. The output in my test is this:
```xml
<UBLDocumentSignatures xmlns="urn:oasis:names:specification:ubl:schema:xsd:CommonSignatureComponents-2">
  <ns0:SignatureInformation xmlns:ns0="urn:oasis:names:specification:ubl:schema:xsd:SignatureAggregateComponents-2">
    <ns1:Signature xmlns:ns1="http://www.w3.org/2000/09/xmldsig#">
      <ns1:SignedInfo Id="bla">
        <ns1:CanonicalizationMethod Algorithm="bla" />
        <ns1:SignatureMethod Algorithm="bla" />
        <ns1:Reference>
          <ns1:DigestMethod Algorithm="urn:bla" />
          <ns1:DigestValue>YWJj</ns1:DigestValue>
        </ns1:Reference>
      </ns1:SignedInfo>
      <ns1:SignatureValue>ZGVm</ns1:SignatureValue>
      <ns1:Object>
        <ns2:QualifyingProperties xmlns:ns2="http://uri.etsi.org/01903/v1.3.2#" Target="signature">
          <ns2:SignedProperties Id="id-xades-signed-props">
            <ns2:SignedSignatureProperties>
              <ns2:SigningTime>2024-12-18T11:41:47.841</ns2:SigningTime>
              <ns2:SigningCertificate>
                <ns2:Cert>
                  <ns2:CertDigest>
                    <ns1:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                    <ns1:DigestValue>WVRKa00ySmhZVGN3WlRCaFpUQXhPR1l3T0RNeU56WTNOVGRrWkRNM1l6aGpZMkl4T1RJeVpEWmhNMlJsWkdKaU1HWTBORFV6WldKaFlXSTRNRGhtWWc9PQ==</ns1:DigestValue>
                  </ns2:CertDigest>
                  <ns2:IssuerSerial>
                    <ns1:X509IssuerName>CN = Contoso Malaysia Sdn Bhd, E = noemail@contoso.com, OU = Contoso Malaysia Sdn Bhd, O = Contoso Malaysia Sdn Bhd, C = MY</ns1:X509IssuerName>
                    <ns1:X509SerialNumber>2475382886904809774818644480820936050208702411</ns1:X509SerialNumber>
                  </ns2:IssuerSerial>
                </ns2:Cert>
              </ns2:SigningCertificate>
            </ns2:SignedSignatureProperties>
          </ns2:SignedProperties>
        </ns2:QualifyingProperties>
      </ns1:Object>
    </ns1:Signature>
  </ns0:SignatureInformation>
</UBLDocumentSignatures>
```

**Comment by hyououou** [comment]
Thank you very much for your help.
The problem has been solved.
You're amazing.
