### ISSUE TITLE
Generate Ubl

### ISSUE THREAD

**Issue by carlosthe19916** [phax/ph-ubl#8]
Hi, i saw that this library is usefull for write and read Ubl(existed) documents, but i can't find any class to GENERATE ubl documents, can i use this library for GENERATE Ubl, could you give me a suggestion please.

**Comment by phax** [comment]
Hi! You mean you create the UBL document in memory and than rite it to disk? Or what do you mean with "generate"? You just create e.g. an `InvoiceType` object in memory, fill all the necessary fields and than call `UBL21Writer.invoice().write (invoice, file)`.
If you want to map from another format to UBL, you need to implement that mapping logic on your own.
This library is just a very thin layer above UBL - it doesn't contain any mgaic :)

**Comment by carlosthe19916** [comment]
Yes i needed to create an InvoiceType, now i know how to build that...Thanks a lot!!! i'm just starting with the ubl standard and this library is awsome.
