### ISSUE TITLE
ph-ubl-jaxb-plugin example

### ISSUE THREAD

**Issue by carlosthe19916** [phax/ph-ubl#9]
Hi!!! Is there any example about hot to use ph-ubl-jaxb-plugin? please could you let me know if is there any example using ph-ubl-jaxb-plugin? i need to add custom methods to Ubl specification...

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
The ph-ubl-jaxb-plugin is internally used in the ph-ubl20 and ph-ubl21 plugin (see the pom.xml files).
It is used to create some sanity methods to simplify the creation.
What exactly do you have in mind?

**Comment by phax** [comment]
Did you find what you are looking for?

**Comment by carlosthe19916** [comment]
I was trying to generate java classes from my own XSD and combine it with ph-ubl classes.....thank you very much!!!!!!, I could generate java classes using maven plugin.
